// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file was automatically generated by the XDK build tool.
 * Any manual changes will be overwritten on the next generation.
 * 
 * Auto-generated generic tests for Webhooks client.
 *
 * This module contains general tests that validate the overall client
 * functionality, imports, error handling, and common behavior patterns
 * that apply across all operations without being operation-specific.
 *
 * Generated automatically - do not edit manually.
 */

import { describe, it, expect, beforeAll, jest } from '@jest/globals';
import { WebhooksClient } from '../../src/webhooks/client.js';
import { Client, ApiError } from '../../src/client.js';

describe('WebhooksClient Generic', () => {
  let client: Client;
  let webhooksClient: WebhooksClient;

  beforeAll(() => {
    client = new Client({ baseUrl: 'https://api.example.com' });
    webhooksClient = client.webhooks;
  });

  it('should have WebhooksClient class that is importable', () => {
    expect(WebhooksClient).toBeDefined();
    expect(typeof WebhooksClient).toBe('function');
  });

  it('should initialize WebhooksClient properly', () => {
    expect(webhooksClient).toBeDefined();
    expect(webhooksClient).toBeInstanceOf(WebhooksClient);
  });

  it('should have expected base functionality', () => {
    // Should be able to access the client through main Client
    expect(client).toHaveProperty('webhooks');
    
    // Client should have standard object features
    expect(webhooksClient).toHaveProperty('constructor');
    
    // Should have at least one public method
    const publicMethods = Object.getOwnPropertyNames(WebhooksClient.prototype)
      .filter(name => !name.startsWith('_') && name !== 'constructor');
    
    expect(publicMethods.length).toBeGreaterThan(0);
  });

  it('should handle error responses correctly', async () => {
    // Mock validateAuthentication to bypass auth checks (like Python mocks session)
    const originalValidateAuth = client.validateAuthentication;
    client.validateAuthentication = jest.fn();
    
    // Mock httpClient.request to return error response (like Python mocks session)
    const originalRequest = client.httpClient.request;
    (client.httpClient.request as any) = jest.fn().mockResolvedValue({
      ok: false,
      status: 404,
      statusText: 'Not Found',
      headers: new Headers(),
      json: async () => ({
        title: 'Not Found',
        type: 'about:blank',
        status: 404,
        detail: 'Not Found'
      }),
      text: async () => 'Not Found'
    } as Response);

    try {
      // Get first available method for testing error handling
      const publicMethods = Object.getOwnPropertyNames(WebhooksClient.prototype)
        .filter(name => !name.startsWith('_') && name !== 'constructor');
      
      if (publicMethods.length > 0) {
        const methodName = publicMethods[0];
        const method = (webhooksClient as any)[methodName];
        
        // Try calling the method and expect an ApiError
        await expect(method.call(webhooksClient)).rejects.toThrow(ApiError);
      }
    } finally {
      client.httpClient.request = originalRequest;
      client.validateAuthentication = originalValidateAuth;
    }
  });

  it('should have valid method signatures', () => {
    const publicMethods = Object.getOwnPropertyNames(WebhooksClient.prototype)
      .filter(name => !name.startsWith('_') && name !== 'constructor');
    
    for (const methodName of publicMethods) {
      const method = (WebhooksClient.prototype as any)[methodName];
      expect(typeof method).toBe('function');
      
      // Should be able to get method string representation
      const methodString = method.toString();
      expect(methodString).toBeTruthy();
    }
  });
});
