// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * Stream client for the X API.
 *
 * This module provides a client for interacting with the streaming endpoints of the X API.
 */

import { Client, ApiResponse, RequestOptions } from '../client.js';
import type * as Schemas from '../schemas.js';
import { EventDrivenStream, StreamEvent } from './event_driven_stream.js';
import {


  ArticleCreateDraftResponse,



  ArticlePublishResponse,

} from './models.js';

/**
 * Options for articleCreateDraft method
 * 
 * @public
 */
export interface ArticleCreateDraftStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for articlePublish method
 * 
 * @public
 */
export interface ArticlePublishStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}


export class ArticlesClient {
    private client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * Normalize options object to handle both camelCase and original API parameter names
     * Only accepts: proper camelCase (tweetFields) and original API format (tweet.fields)
     */
    private _normalizeOptions<T extends Record<string, any>>(options: T, paramMappings: Record<string, string>): T {
        if (!options || typeof options !== 'object') {
            return options;
        }
        
        const normalized: any = { ...options };
        
        // For each parameter mapping (original -> proper camelCase)
        for (const [originalName, camelName] of Object.entries(paramMappings)) {
            // Check if original format is used (e.g., 'tweet.fields', 'tweet_fields')
            if (originalName in normalized && !(camelName in normalized)) {
                normalized[camelName] = normalized[originalName];
                delete normalized[originalName];
            }
            // Also check for proper camelCase (e.g., 'tweetFields')
            // If it's already in proper camelCase, keep it (no conversion needed)
            // The camelName is already the proper camelCase format
        }
        
        return normalized as T;
    }











    /**
     * Create draft Article
     * Creates a new Article draft that can later be published.
     * 
     * @returns Promise with the API response
     */
    async articleCreateDraft(
        
        
        
        
        
        
        body: any,
        
        
        options: ArticleCreateDraftStreamingOptions = {}
    ): Promise<ArticleCreateDraftResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'articleCreateDraft');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/articles/draft';
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<ArticleCreateDraftResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Publish Article
     * Publishes a draft Article, making it publicly visible.
     * 
     * @returns Promise with the API response
     */
    async articlePublish(
        
        
        
        articleId: string,
        
        
        
        
        
        
        
        options: ArticlePublishStreamingOptions = {}
    ): Promise<ArticlePublishResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'articlePublish');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/articles/{article_id}/publish';
        
        
        path = path.replace('{article_id}', encodeURIComponent(String(articleId)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<ArticlePublishResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }


}