// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * Stream client for the X API.
 *
 * This module provides a client for interacting with the streaming endpoints of the X API.
 */

import { Client, ApiResponse, RequestOptions } from '../client.js';
import type * as Schemas from '../schemas.js';
import { EventDrivenStream, StreamEvent } from './event_driven_stream.js';
import {


  MediaUploadAppendResponse,



  AddConversationKeysResponse,



  AddGroupMembersResponse,



  MarkConversationReadResponse,



  AddUserPublicKeyResponse,



  GetConversationsResponse,



  InitializeGroupResponse,



  SendMessageResponse,



  MediaUploadInitializeResponse,



  SendTypingIndicatorResponse,



  GetConversationEventsResponse,



  GetConversationResponse,



  CreateConversationResponse,





  MediaUploadFinalizeResponse,

} from './models.js';

/**
 * Options for mediaUploadAppend method
 * 
 * @public
 */
export interface MediaUploadAppendStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for addConversationKeys method
 * 
 * @public
 */
export interface AddConversationKeysStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for addGroupMembers method
 * 
 * @public
 */
export interface AddGroupMembersStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for markConversationRead method
 * 
 * @public
 */
export interface MarkConversationReadStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for addUserPublicKey method
 * 
 * @public
 */
export interface AddUserPublicKeyStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for getConversations method
 * 
 * @public
 */
export interface GetConversationsStreamingOptions {
    
    
    /** Maximum number of conversations to return. 
     * Also accepts: max_results or proper camelCase (e.g., maxResults) */
    maxResults?: number;
    
    
    
    /** Token for pagination to retrieve the next page of results. 
     * Also accepts: pagination_token or proper camelCase (e.g., paginationToken) */
    paginationToken?: string;
    
    
    
    /** A comma separated list of ChatConversation fields to display. 
     * Also accepts: chat_conversation.fields or proper camelCase (e.g., chatConversationFields) */
    chatConversationFields?: Array<"admin_ids" | "created_at" | "group_avatar_url" | "group_name" | "id" | "is_muted" | "member_ids" | "message_ttl_msec" | "participant_ids" | "screen_capture_blocking_enabled" | "screen_capture_detection_enabled" | "type" | "updated_at">;
    
    
    
    /** A comma separated list of fields to expand. 
     * Also accepts: expansions or proper camelCase (e.g., expansions) */
    expansions?: Array<"admin_ids" | "member_ids" | "participant_ids">;
    
    
    
    /** A comma separated list of User fields to display. 
     * Also accepts: user.fields or proper camelCase (e.g., userFields) */
    userFields?: Array<"affiliation" | "confirmed_email" | "connection_status" | "created_at" | "description" | "entities" | "id" | "is_identity_verified" | "location" | "most_recent_tweet_id" | "name" | "parody" | "pinned_tweet_id" | "profile_banner_url" | "profile_image_url" | "protected" | "public_metrics" | "receives_your_dm" | "subscription" | "subscription_type" | "url" | "username" | "verified" | "verified_followers_count" | "verified_type" | "withheld">;
    
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for initializeGroup method
 * 
 * @public
 */
export interface InitializeGroupStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for sendMessage method
 * 
 * @public
 */
export interface SendMessageStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for mediaUploadInitialize method
 * 
 * @public
 */
export interface MediaUploadInitializeStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for sendTypingIndicator method
 * 
 * @public
 */
export interface SendTypingIndicatorStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for getConversationEvents method
 * 
 * @public
 */
export interface GetConversationEventsStreamingOptions {
    
    
    /** Maximum number of message events to return. 
     * Also accepts: max_results or proper camelCase (e.g., maxResults) */
    maxResults?: number;
    
    
    
    /** Token for pagination to retrieve the next page of results. 
     * Also accepts: pagination_token or proper camelCase (e.g., paginationToken) */
    paginationToken?: string;
    
    
    
    /** A comma separated list of ChatMessageEvent fields to display. 
     * Also accepts: chat_message_event.fields or proper camelCase (e.g., chatMessageEventFields) */
    chatMessageEventFields?: Array<"conversation_id" | "conversation_token" | "created_at_msec" | "encoded_event" | "id" | "is_trusted" | "message_event_signature" | "previous_id" | "sender_id">;
    
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for getConversation method
 * 
 * @public
 */
export interface GetConversationStreamingOptions {
    
    
    /** A comma separated list of ChatConversation fields to display. 
     * Also accepts: chat_conversation.fields or proper camelCase (e.g., chatConversationFields) */
    chatConversationFields?: Array<"admin_ids" | "created_at" | "group_avatar_url" | "group_name" | "id" | "is_muted" | "member_ids" | "message_ttl_msec" | "participant_ids" | "screen_capture_blocking_enabled" | "screen_capture_detection_enabled" | "type" | "updated_at">;
    
    
    
    /** A comma separated list of fields to expand. 
     * Also accepts: expansions or proper camelCase (e.g., expansions) */
    expansions?: Array<"admin_ids" | "member_ids" | "participant_ids">;
    
    
    
    /** A comma separated list of User fields to display. 
     * Also accepts: user.fields or proper camelCase (e.g., userFields) */
    userFields?: Array<"affiliation" | "confirmed_email" | "connection_status" | "created_at" | "description" | "entities" | "id" | "is_identity_verified" | "location" | "most_recent_tweet_id" | "name" | "parody" | "pinned_tweet_id" | "profile_banner_url" | "profile_image_url" | "protected" | "public_metrics" | "receives_your_dm" | "subscription" | "subscription_type" | "url" | "username" | "verified" | "verified_followers_count" | "verified_type" | "withheld">;
    
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for createConversation method
 * 
 * @public
 */
export interface CreateConversationStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for mediaDownload method
 * 
 * @public
 */
export interface MediaDownloadStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}
/**
 * Options for mediaUploadFinalize method
 * 
 * @public
 */
export interface MediaUploadFinalizeStreamingOptions {
    
    
    /** Additional request options */
    requestOptions?: RequestOptions;
    /** Additional headers */
    headers?: Record<string, string>;
    /** AbortSignal for cancelling the request */
    signal?: AbortSignal;
    /** Allow original API parameter names (e.g., 'tweet.fields', 'user.fields') and proper camelCase (e.g., 'tweetFields', 'userFields') */
    [key: string]: any;
}


export class ChatClient {
    private client: Client;

    constructor(client: Client) {
        this.client = client;
    }

    /**
     * Normalize options object to handle both camelCase and original API parameter names
     * Only accepts: proper camelCase (tweetFields) and original API format (tweet.fields)
     */
    private _normalizeOptions<T extends Record<string, any>>(options: T, paramMappings: Record<string, string>): T {
        if (!options || typeof options !== 'object') {
            return options;
        }
        
        const normalized: any = { ...options };
        
        // For each parameter mapping (original -> proper camelCase)
        for (const [originalName, camelName] of Object.entries(paramMappings)) {
            // Check if original format is used (e.g., 'tweet.fields', 'tweet_fields')
            if (originalName in normalized && !(camelName in normalized)) {
                normalized[camelName] = normalized[originalName];
                delete normalized[originalName];
            }
            // Also check for proper camelCase (e.g., 'tweetFields')
            // If it's already in proper camelCase, keep it (no conversion needed)
            // The camelName is already the proper camelCase format
        }
        
        return normalized as T;
    }


















































    /**
     * Append Chat Media Upload
     * Appends media data to an XChat upload session.
     * 
     * @returns Promise with the API response
     */
    async mediaUploadAppend(
        
        
        
        id: string,
        
        
        
        
        
        
        body: any,
        
        
        options: MediaUploadAppendStreamingOptions = {}
    ): Promise<MediaUploadAppendResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'mediaUploadAppend');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/media/upload/{id}/append';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<MediaUploadAppendResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Add Conversation Keys
     * Adds (initializes or rotates) the encryption keys for a Chat conversation.
Call this before sending messages in a new 1:1 conversation, and again with a
newer key version to rotate the conversation key.

For 1:1 conversations, provide the recipient's user ID as the conversation_id.
The server constructs the canonical conversation ID from the authenticated user
and recipient.

The request body must contain the conversation key version and participant keys
(the conversation key encrypted for each participant using their public key).

**Workflow (new 1:1 conversation):**
1. Generate a conversation key using the SDK
2. Encrypt the key for both participants using their public keys
3. Call this endpoint to register the keys
4. Send messages using `POST /chat/conversations/{id}/messages`

To rotate the keys of an existing conversation, repeat the same call with a
newer conversation key version.

**Authentication:**
- Requires OAuth 1.0a User Context or OAuth 2.0 User Context
- Required scopes: `tweet.read`, `users.read`, `dm.write`

     * 
     * @returns Promise with the API response
     */
    async addConversationKeys(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        body: any,
        
        
        options: AddConversationKeysStreamingOptions = {}
    ): Promise<AddConversationKeysResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'addConversationKeys');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/keys';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<AddConversationKeysResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Add members to a Chat group conversation
     * Adds one or more members to an existing encrypted Chat group conversation, rotating the conversation key.
     * 
     * @returns Promise with the API response
     */
    async addGroupMembers(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        body: any,
        
        
        options: AddGroupMembersStreamingOptions = {}
    ): Promise<AddGroupMembersResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'addGroupMembers');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/members';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<AddGroupMembersResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Mark Conversation as Read
     * Marks a specific Chat conversation as read on behalf of the authenticated user. For 1:1 conversations, provide the recipient's user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
     * 
     * @returns Promise with the API response
     */
    async markConversationRead(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        body: any,
        
        
        options: MarkConversationReadStreamingOptions = {}
    ): Promise<MarkConversationReadResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'markConversationRead');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/read';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<MarkConversationReadResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Add public key
     * Registers a user's public key for X Chat encryption.
     * 
     * @returns Promise with the API response
     */
    async addUserPublicKey(
        
        
        
        id: Schemas.UserId,
        
        
        
        
        
        
        body: any,
        
        
        options: AddUserPublicKeyStreamingOptions = {}
    ): Promise<AddUserPublicKeyResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'addUserPublicKey');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/users/{id}/public_keys';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<AddUserPublicKeyResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Get Chat Conversations
     * Retrieves a list of Chat conversations for the authenticated user's inbox.
     * 
     * @returns Promise with the API response
     */
    async getConversations(
        
        
        
        
        
        
        
        options: GetConversationsStreamingOptions = {}
    ): Promise<GetConversationsResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'getConversations');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const paramMappings: Record<string, string> = {
            
            
            'max_results': 'maxResults',
            
            
            
            'pagination_token': 'paginationToken',
            
            
            
            'chat_conversation.fields': 'chatConversationFields',
            
            
            
            
            
            'user.fields': 'userFields',
            
            
        };
        const normalizedOptions = this._normalizeOptions(options || {}, paramMappings);
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const {
            
            
            maxResults = undefined,
            
            
            
            paginationToken = undefined,
            
            
            
            chatConversationFields = [],
            
            
            
            expansions = [],
            
            
            
            userFields = [],
            
            
            
            headers = {},
            signal,
            requestOptions: requestOptions = {}
        } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations';
        

        // Build query parameters
        const params = new URLSearchParams();
        
        
        
        
        
        if (maxResults !== undefined) {
            
            params.append('max_results', String(maxResults));
            
        }
        
        
        
        
        
        
        
        if (paginationToken !== undefined) {
            
            params.append('pagination_token', String(paginationToken));
            
        }
        
        
        
        
        
        
        
        if (chatConversationFields !== undefined && chatConversationFields.length > 0) {
            
            params.append('chat_conversation.fields', chatConversationFields.join(','));
            
        }
        
        
        
        
        
        
        
        if (expansions !== undefined && expansions.length > 0) {
            
            params.append('expansions', expansions.join(','));
            
        }
        
        
        
        
        
        
        
        if (userFields !== undefined && userFields.length > 0) {
            
            params.append('user.fields', userFields.join(','));
            
        }
        
        
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<GetConversationsResponse>(
            'GET',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Initialize Chat Group
     * Initializes a new XChat group conversation and returns a unique conversation ID.

This endpoint is the first step in creating a group chat. The returned conversation_id 
should be used in subsequent calls to POST /chat/conversations/group to fully create and 
configure the group with members, admins, encryption keys, and other settings.

**Workflow:**
1. Call this endpoint to get a `conversation_id`
2. Use that `conversation_id` when calling `POST /chat/conversations/group` to create the group

**Authentication:**
- Requires OAuth 1.0a User Context or OAuth 2.0 User Context
- Required scope: `dm.write`

     * 
     * @returns Promise with the API response
     */
    async initializeGroup(
        
        
        
        
        
        
        
        options: InitializeGroupStreamingOptions = {}
    ): Promise<InitializeGroupResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'initializeGroup');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/group/initialize';
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<InitializeGroupResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Send Chat Message
     * Sends an encrypted message to a specific Chat conversation. For 1:1 conversations, provide the recipient's user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
     * 
     * @returns Promise with the API response
     */
    async sendMessage(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        body: any,
        
        
        options: SendMessageStreamingOptions = {}
    ): Promise<SendMessageResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'sendMessage');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/messages';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<SendMessageResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Initialize Chat Media Upload
     * Initializes an XChat media upload session.
     * 
     * @returns Promise with the API response
     */
    async mediaUploadInitialize(
        
        
        
        
        
        
        body: any,
        
        
        options: MediaUploadInitializeStreamingOptions = {}
    ): Promise<MediaUploadInitializeResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'mediaUploadInitialize');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/media/upload/initialize';
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<MediaUploadInitializeResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Send Typing Indicator
     * Sends a typing indicator to a specific Chat conversation on behalf of the authenticated user. For 1:1 conversations, provide the recipient's user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
     * 
     * @returns Promise with the API response
     */
    async sendTypingIndicator(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        
        options: SendTypingIndicatorStreamingOptions = {}
    ): Promise<SendTypingIndicatorResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'sendTypingIndicator');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/typing';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<SendTypingIndicatorResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Get Chat Conversation Events
     * Retrieves messages and key change events for a specific Chat conversation with pagination support. For 1:1 conversations, provide the recipient's user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
     * 
     * @returns Promise with the API response
     */
    async getConversationEvents(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        
        
        
        
        options: GetConversationEventsStreamingOptions = {}
    ): Promise<GetConversationEventsResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'getConversationEvents');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const paramMappings: Record<string, string> = {
            
            
            'max_results': 'maxResults',
            
            
            
            'pagination_token': 'paginationToken',
            
            
            
            'chat_message_event.fields': 'chatMessageEventFields',
            
            
        };
        const normalizedOptions = this._normalizeOptions(options || {}, paramMappings);
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const {
            
            
            maxResults = undefined,
            
            
            
            paginationToken = undefined,
            
            
            
            chatMessageEventFields = [],
            
            
            
            headers = {},
            signal,
            requestOptions: requestOptions = {}
        } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}/events';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        
        
        
        
        
        if (maxResults !== undefined) {
            
            params.append('max_results', String(maxResults));
            
        }
        
        
        
        
        
        
        
        if (paginationToken !== undefined) {
            
            params.append('pagination_token', String(paginationToken));
            
        }
        
        
        
        
        
        
        
        if (chatMessageEventFields !== undefined && chatMessageEventFields.length > 0) {
            
            params.append('chat_message_event.fields', chatMessageEventFields.join(','));
            
        }
        
        
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<GetConversationEventsResponse>(
            'GET',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Get Chat Conversation
     * Returns metadata for a Chat conversation including type, muted status, and group details. Use chat_conversation.fields to select which fields are returned. Use expansions to hydrate member, admin, or participant user objects. Use user.fields to control which profile fields are returned for expanded users.
     * 
     * @returns Promise with the API response
     */
    async getConversation(
        
        
        
        id: string,
        
        
        
        
        
        
        
        options: GetConversationStreamingOptions = {}
    ): Promise<GetConversationResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'getConversation');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const paramMappings: Record<string, string> = {
            
            
            'chat_conversation.fields': 'chatConversationFields',
            
            
            
            
            
            'user.fields': 'userFields',
            
            
        };
        const normalizedOptions = this._normalizeOptions(options || {}, paramMappings);
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const {
            
            
            chatConversationFields = [],
            
            
            
            expansions = [],
            
            
            
            userFields = [],
            
            
            
            headers = {},
            signal,
            requestOptions: requestOptions = {}
        } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/{id}';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        
        
        
        
        
        if (chatConversationFields !== undefined && chatConversationFields.length > 0) {
            
            params.append('chat_conversation.fields', chatConversationFields.join(','));
            
        }
        
        
        
        
        
        
        
        if (expansions !== undefined && expansions.length > 0) {
            
            params.append('expansions', expansions.join(','));
            
        }
        
        
        
        
        
        
        
        if (userFields !== undefined && userFields.length > 0) {
            
            params.append('user.fields', userFields.join(','));
            
        }
        
        
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<GetConversationResponse>(
            'GET',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Create Chat Group Conversation
     * Creates a new encrypted Chat group conversation on behalf of the authenticated user.
     * 
     * @returns Promise with the API response
     */
    async createConversation(
        
        
        
        
        
        
        body: any,
        
        
        options: CreateConversationStreamingOptions = {}
    ): Promise<CreateConversationResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'createConversation');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/conversations/group';
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<CreateConversationResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Download Chat Media
     * Downloads encrypted media bytes from an XChat conversation. The response body contains raw binary bytes. For 1:1 conversations, provide the recipient's user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
     * 
     * @returns Promise with the API response
     */
    async mediaDownload(
        
        
        
        id: Schemas.ChatConversationOrRecipientId,
        
        
        
        mediaHashKey: Schemas.MediaHashKey,
        
        
        
        
        
        
        
        options: MediaDownloadStreamingOptions = {}
    ): Promise<any> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'mediaDownload');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/media/{id}/{media_hash_key}';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        
        
        path = path.replace('{media_hash_key}', encodeURIComponent(String(mediaHashKey)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<any>(
            'GET',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }



    /**
     * Finalize Chat Media Upload
     * Finalizes an XChat media upload session.
     * 
     * @returns Promise with the API response
     */
    async mediaUploadFinalize(
        
        
        
        id: string,
        
        
        
        
        
        
        body: any,
        
        
        options: MediaUploadFinalizeStreamingOptions = {}
    ): Promise<MediaUploadFinalizeResponse> {
        // Validate authentication requirements
        
        const requiredAuthTypes = [];
        
        
        requiredAuthTypes.push('OAuth2UserToken');
        
        
        
        requiredAuthTypes.push('UserToken');
        
        
        this.client.validateAuthentication(requiredAuthTypes, 'mediaUploadFinalize');
        

        // Normalize options to handle both camelCase and original API parameter names
        
        const normalizedOptions = options || {};
        

        // Destructure options (exclude path parameters, they're already function params)
        
        const { headers = {}, signal, requestOptions = {} } = normalizedOptions;
        

        // Build the path with path parameters
        let path = '/2/chat/media/upload/{id}/finalize';
        
        
        path = path.replace('{id}', encodeURIComponent(String(id)));
        
        

        // Build query parameters
        const params = new URLSearchParams();
        

        // Prepare request options
        const finalRequestOptions: RequestOptions = {
            headers: {
                'Content-Type': 'application/json',
                ...headers,
            },
            signal: signal,
            
            body: JSON.stringify(body),
            
            ...requestOptions,
        };

        // Make the request
        return this.client.request<MediaUploadFinalizeResponse>(
            'POST',
            path + (params.toString() ? `?${params.toString()}` : ''),
            finalRequestOptions
        );
    }


}