// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file was automatically generated by the XDK build tool.
 * Any manual changes will be overwritten on the next generation.
 * 
 * Auto-generated structural tests for CommunityNotes client.
 *
 * This module contains tests that validate the structure and API surface
 * of the CommunityNotes client. These tests ensure that all expected methods
 * exist, have correct signatures, and proper type annotations for robust API contracts.
 *
 * Generated automatically - do not edit manually.
 */

import { describe, it, expect, beforeAll } from '@jest/globals';
import { CommunityNotesClient } from '../../src/community_notes/client.js';
import { Client } from '../../src/client.js';

describe('CommunityNotesClient Structure', () => {
  let client: Client;
  let communityNotesClient: CommunityNotesClient;

  beforeAll(() => {
    client = new Client({ baseUrl: 'https://api.example.com' });
    communityNotesClient = client.communityNotes;
  });

  
  
  it('should have evaluate method with correct signature', () => {
    // Check method exists
    expect(CommunityNotesClient.prototype).toHaveProperty('evaluate');
    
    // Check method is callable
    const method = communityNotesClient.evaluate;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have evaluate method with return type annotation', () => {
    const method = communityNotesClient.evaluate;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have create method with correct signature', () => {
    // Check method exists
    expect(CommunityNotesClient.prototype).toHaveProperty('create');
    
    // Check method is callable
    const method = communityNotesClient.create;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have create method with return type annotation', () => {
    const method = communityNotesClient.create;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have searchWritten method with correct signature', () => {
    // Check method exists
    expect(CommunityNotesClient.prototype).toHaveProperty('searchWritten');
    
    // Check method is callable
    const method = communityNotesClient.searchWritten;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'testMode',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have searchWritten method with return type annotation', () => {
    const method = communityNotesClient.searchWritten;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  
  it('should have searchWritten method with pagination parameters', () => {
    const method = communityNotesClient.searchWritten;
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Should have pagination-related parameters (check for common pagination param names)
    const paginationKeywords = ['pagination', 'token', 'max', 'results', 'next', 'cursor', 'limit', 'page'];
    const hasPaginationParam = paginationKeywords.some(keyword => 
      params.some(p => p.toLowerCase().includes(keyword.toLowerCase()))
    );
    // Note: Some pagination methods may use options object instead of individual params
    // This test is lenient to account for different pagination patterns
    if (params.length > 0) {
      expect(hasPaginationParam || params.some(p => p.includes('options'))).toBe(true);
    }
  });
  

  
  it('should have searchEligiblePosts method with correct signature', () => {
    // Check method exists
    expect(CommunityNotesClient.prototype).toHaveProperty('searchEligiblePosts');
    
    // Check method is callable
    const method = communityNotesClient.searchEligiblePosts;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'testMode',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have searchEligiblePosts method with return type annotation', () => {
    const method = communityNotesClient.searchEligiblePosts;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  
  it('should have searchEligiblePosts method with pagination parameters', () => {
    const method = communityNotesClient.searchEligiblePosts;
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Should have pagination-related parameters (check for common pagination param names)
    const paginationKeywords = ['pagination', 'token', 'max', 'results', 'next', 'cursor', 'limit', 'page'];
    const hasPaginationParam = paginationKeywords.some(keyword => 
      params.some(p => p.toLowerCase().includes(keyword.toLowerCase()))
    );
    // Note: Some pagination methods may use options object instead of individual params
    // This test is lenient to account for different pagination patterns
    if (params.length > 0) {
      expect(hasPaginationParam || params.some(p => p.includes('options'))).toBe(true);
    }
  });
  

  
  it('should have delete method with correct signature', () => {
    // Check method exists
    expect(CommunityNotesClient.prototype).toHaveProperty('delete');
    
    // Check method is callable
    const method = communityNotesClient.delete;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'id',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have delete method with return type annotation', () => {
    const method = communityNotesClient.delete;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  

  it('should have all expected methods', () => {
    const expectedMethods = [
      
      'evaluate',
      
      'create',
      
      'searchWritten',
      
      'searchEligiblePosts',
      
      'delete',
      
    ];

    for (const expectedMethod of expectedMethods) {
      expect(CommunityNotesClient.prototype).toHaveProperty(expectedMethod);
      const method = (communityNotesClient as any)[expectedMethod];
      expect(typeof method).toBe('function');
    }
  });

  
});
