// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file was automatically generated by the XDK build tool.
 * Any manual changes will be overwritten on the next generation.
 * 
 * Auto-generated structural tests for Spaces client.
 *
 * This module contains tests that validate the structure and API surface
 * of the Spaces client. These tests ensure that all expected methods
 * exist, have correct signatures, and proper type annotations for robust API contracts.
 *
 * Generated automatically - do not edit manually.
 */

import { describe, it, expect, beforeAll } from '@jest/globals';
import { SpacesClient } from '../../src/spaces/client.js';
import { Client } from '../../src/client.js';

describe('SpacesClient Structure', () => {
  let client: Client;
  let spacesClient: SpacesClient;

  beforeAll(() => {
    client = new Client({ baseUrl: 'https://api.example.com' });
    spacesClient = client.spaces;
  });

  
  
  it('should have getById method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('getById');
    
    // Check method is callable
    const method = spacesClient.getById;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'id',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have getById method with return type annotation', () => {
    const method = spacesClient.getById;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have getByCreatorIds method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('getByCreatorIds');
    
    // Check method is callable
    const method = spacesClient.getByCreatorIds;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'userIds',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have getByCreatorIds method with return type annotation', () => {
    const method = spacesClient.getByCreatorIds;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have getByIds method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('getByIds');
    
    // Check method is callable
    const method = spacesClient.getByIds;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'ids',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have getByIds method with return type annotation', () => {
    const method = spacesClient.getByIds;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have search method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('search');
    
    // Check method is callable
    const method = spacesClient.search;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'query',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have search method with return type annotation', () => {
    const method = spacesClient.search;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have getPosts method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('getPosts');
    
    // Check method is callable
    const method = spacesClient.getPosts;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'id',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have getPosts method with return type annotation', () => {
    const method = spacesClient.getPosts;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  
  it('should have getBuyers method with correct signature', () => {
    // Check method exists
    expect(SpacesClient.prototype).toHaveProperty('getBuyers');
    
    // Check method is callable
    const method = spacesClient.getBuyers;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
      'id',
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have getBuyers method with return type annotation', () => {
    const method = spacesClient.getBuyers;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  
  it('should have getBuyers method with pagination parameters', () => {
    const method = spacesClient.getBuyers;
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Should have pagination-related parameters (check for common pagination param names)
    const paginationKeywords = ['pagination', 'token', 'max', 'results', 'next', 'cursor', 'limit', 'page'];
    const hasPaginationParam = paginationKeywords.some(keyword => 
      params.some(p => p.toLowerCase().includes(keyword.toLowerCase()))
    );
    // Note: Some pagination methods may use options object instead of individual params
    // This test is lenient to account for different pagination patterns
    if (params.length > 0) {
      expect(hasPaginationParam || params.some(p => p.includes('options'))).toBe(true);
    }
  });
  

  

  it('should have all expected methods', () => {
    const expectedMethods = [
      
      'getById',
      
      'getByCreatorIds',
      
      'getByIds',
      
      'search',
      
      'getPosts',
      
      'getBuyers',
      
    ];

    for (const expectedMethod of expectedMethods) {
      expect(SpacesClient.prototype).toHaveProperty(expectedMethod);
      const method = (spacesClient as any)[expectedMethod];
      expect(typeof method).toBe('function');
    }
  });

  
});
