// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file was automatically generated by the XDK build tool.
 * Any manual changes will be overwritten on the next generation.
 * 
 * Auto-generated structural tests for Usage client.
 *
 * This module contains tests that validate the structure and API surface
 * of the Usage client. These tests ensure that all expected methods
 * exist, have correct signatures, and proper type annotations for robust API contracts.
 *
 * Generated automatically - do not edit manually.
 */

import { describe, it, expect, beforeAll } from '@jest/globals';
import { UsageClient } from '../../src/usage/client.js';
import { Client } from '../../src/client.js';

describe('UsageClient Structure', () => {
  let client: Client;
  let usageClient: UsageClient;

  beforeAll(() => {
    client = new Client({ baseUrl: 'https://api.example.com' });
    usageClient = client.usage;
  });

  
  
  it('should have get method with correct signature', () => {
    // Check method exists
    expect(UsageClient.prototype).toHaveProperty('get');
    
    // Check method is callable
    const method = usageClient.get;
    expect(typeof method).toBe('function');
    
    // Check method signature by examining parameter count
    const methodString = method.toString();
    const paramsMatch = methodString.match(/\(([^)]*)\)/);
    const params = paramsMatch ? paramsMatch[1].split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p) : [];
    
    // Check required parameters exist (convert to camelCase for TypeScript)
    const requiredParams = [
      
    ];
    
    for (const requiredParam of requiredParams) {
      // Check if parameter exists (may be in camelCase or snake_case)
      const paramExists = params.some(p => 
        p === requiredParam || 
        p.toLowerCase() === requiredParam.toLowerCase() ||
        p.replace(/_/g, '') === requiredParam.replace(/_/g, '')
      );
      expect(paramExists).toBe(true);
    }
  });

  it('should have get method with return type annotation', () => {
    const method = usageClient.get;
    expect(typeof method).toBe('function');
    // TypeScript will enforce return types at compile time
    // This test ensures the method exists and is callable
  });

  

  

  it('should have all expected methods', () => {
    const expectedMethods = [
      
      'get',
      
    ];

    for (const expectedMethod of expectedMethods) {
      expect(UsageClient.prototype).toHaveProperty(expectedMethod);
      const method = (usageClient as any)[expectedMethod];
      expect(typeof method).toBe('function');
    }
  });

  
});
