// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by the XDK build tool.
// Any manual changes will be overwritten on the next generation.
/**
 * {"class_name": "Activity", "display_name": "activity", "import_name": "activity", "original": ["activity"], "property_name": "activity"} module for the X API.
 *
 * This module provides a client for interacting with the {"class_name": "Activity", "display_name": "activity", "import_name": "activity", "original": ["activity"], "property_name": "activity"} endpoints of the X API.
 */

export * from './client.js';
export * from './models.js';
